### ISSUE TITLE
Hover zoom

### ISSUE THREAD

**Issue by ryanblumenow** [vivien000/st-clickable-images#1]
Hi there! I was hoping you could add a feature where the image can zoom/enlarge when the user hovers over it?

Similar to this: 

```
<style>
# .zoom {
#   padding: 50px;
#   background-color: yellow;
#   transition: transform .2s; /* Animation */
#   width: 200px;
#   height: 200px;
#   margin: 0 auto;
# }

# .zoom:hover {
#   transform: scale(1.5); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
# }
# </style>

# <div class="zoom"></div>
```

**Comment by vivien000** [comment]
[st-click-detector](https://github.com/vivien000/st-click-detector) is a generalization of st-clickable-images that can be used to achieve this.
