### ISSUE TITLE
Is it possible to box the choosen image?

### ISSUE THREAD

**Issue by sunshineatnoon** [vivien000/st-clickable-images#2]
Hi, Thanks for providing this nice component. It would be nice if we can put the chosen image into a red box so the users know what they choose. Is it possible to implement this? Thanks!

**Comment by vivien000** [comment]
Hi @sunshineatnoon. [st-click-detector](https://github.com/vivien000/st-click-detector) is a generalization of st-clickable-images that could probably be used to achieve this.
