### ISSUE TITLE
Adding Psuedo classes

### ISSUE THREAD

**Issue by GundaSudarrshan** [vivien000/st-clickable-images#3]
This Component is Great!!!!!
this can be improved better by adding Custom Psuedo Properties like :hover, :activated etc.... on those images to make it more customizable to the usecase

**Comment by vivien000** [comment]
Hi @GundaSudarrshan. Thanks for the feedback. I suggest you take a look at [st-click-detector](https://github.com/vivien000/st-click-detector), which is a more general and flexible component and which would allow you to do what you suggest
