### ISSUE TITLE
Instead of URL, can use static images?

### ISSUE THREAD

**Issue by mapattacker** [vivien000/st-clickable-images#5]
As w the title, I want to display static images instead of URL using this library.

However, it gave me this error below.

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/opt/anaconda3/envs/demo/lib/python3.8/site-packages/st_clickable_images/frontend/build/images/sample2.jpg'
```

Wondering if it is possible to do that somehow?

**Comment by vivien000** [comment]
Yes, it's possible but you cannot use the file path directly. Please look at the second example in the QuickStart section of README.md.
