### ISSUE TITLE
Clicking changes the order of images

### ISSUE THREAD

**Issue by bouch20** [vivien000/st-clickable-images#7]
Hi, Thank you for developing these good components.
If a process to reorder images is included, they will be automatically reordered when clicked.
Could you let me know if you have a solution.

I've included the simple code that can be reproduced, version, and video.
```
import random
import streamlit as st
from st_clickable_images import clickable_images

images = [
        "https://images.unsplash.com/photo-1565130838609-c3a86655db61?w=700",
        "https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=700",
        "https://images.unsplash.com/photo-1582550945154-66ea8fff25e1?w=700",
        "https://images.unsplash.com/photo-1591797442444-039f23ddcc14?w=700",
        "https://images.unsplash.com/photo-1518727818782-ed5341dbd476?w=700",
    ]
random.shuffle(images)
clicked = clickable_images(
    images,
    titles=[f"Image #{str(i)}" for i in range(5)],
    div_style={"display": "flex", "justify-content": "center", "flex-wrap": "wrap"},
    img_style={"margin": "5px", "height": "200px"},
)

st.markdown(f"Image #{clicked} clicked" if clicked > -1 else "No image clicked")
```

package version:
``` 
st-clickable-images      0.0.3
streamlit                1.9.0
```

https://user-images.githubusercontent.com/31585230/218269661-f5dd4258-4df4-4cbb-bc57-bbba629e259f.mov

**Comment by bouch20** [comment]
The same result was confirmed with `st-click-detector`

**Comment by vivien000** [comment]
Hi @bouch20. This behavior is expected. By design, "Streamlit reruns your script from top to bottom every time you interact with your app". Since you haven't specified a random seed in your Python code, the order changes every time you interact with the web page. If you add `random.seed(0)` just above `random.shuffle(images)`, you won't have this problem anymore.

**Comment by bouch20** [comment]
Hi @vivien000. Thank you very much for your detailed explanation. I had no idea about this. I will remember to specify the seed value from now on. I will close this issue. Thank you.
